<?php
// module/ntkp/view/ntkp/user/index.phtml
    $title = "Korisnici sistema";
    $this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title) ?></h1>

<table class="table">
    <thead>
        <tr>
            <th>Number</th>
            <th>Name</th>
            <th>Username</th>
            <th>EMail</th>
            <th>Role</th>            
        </tr>
    </thead>
    <tbody>
        <?php foreach($users as $user): ?>
        <tr>
            <td><?php echo $user->id ?></td>
            <td><?php echo $user->name ?></td>
            <td><?php echo $user->username ?></td>
            <td><?php echo $user->email ?></td>
            <td><?php echo $user->role_id ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>