<?php
// module/ntkp/view/ntkp/user/index.phtml
    $this->headLink()->appendStylesheet('/js/jquery-ui/jquery-ui.css');
    $this->headScript()->appendFile('/js/jquery-ui/jquery-ui.js');
    $title = "Korisnici sistema";
    $this->headtitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>

<table class="table">
    <thead>
        <tr>
            <th>R.br.</th>
            <th>Ime</th>
            <th>Korisnicko ime</th>
            <th>e-mail</th>
            <th>Rola</th>       
            <th>Status</th>     
            <th>Subjekt</th>
            <th>Akcija</th>
        </tr>
    </thead>
    
    <tbody>
        <?php foreach($users as $user): ?>
        <tr>
            <td><?= $user->id ?></td>
            <td><?= $user->name ?></td>
            <td><?= $user->username ?></td>
            <td><?= $user->email ?></td>
            <td><?= $user->role_id ?></td>
            <td><?= $user->user_status_id ?></td>
            <?php if($user->company == 'none'):?>
            	<td style="color:red"><?= $user->company ?></td>
            <?php else: ?>
            	<td style="color:blue"><?= $user->company ?></td>
            <?php endif;?>
            <td><a href="<?= $this->url('user', ['action' => 'edit', 'id' => $user->id]) ?>">Edit</a>  |
            <a id="delete" href="<?= $this->url('user', ['action' => 'delete', 'id' => $user->id]) ?>">Delete</a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<div class="modal fade" id="myModal" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title">Brisanje korisnika</h4>
			</div>
			<div class="modal-body">
				<p>Korisnik će biti potpuno obrisan iz baze, bez mogućnosti povratka podataka. Da li ste sigurni?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-confirm" data-dismiss="modal">Yes</button>
				<button type="button" class="btn btn-cancel" data-dismiss="modal">No</button>
			</div>
		</div>
	</div>
</div>
<script>
$(document).ready(function() {
	$('a#delete').on('click', function(e) {
        e.preventDefault();
        path = $(e.target).attr('href');
        //console.log(path);
        $('#myModal').modal('show');
    });

	$('.btn-confirm').on('click', function(e) {        
        //alert(path);
        window.location.href = path;
    });
});
</script>