<?php
// module/ntkp/view/ntkp/user/index.phtml
    $title = "Korisnici sistema";
    $this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title) ?></h1>

<table class="table">
    <thead>
        <tr>
            <th>R.br.</th>
            <th>Ime</th>
            <th>Korisnicko ime</th>
            <th>e-mail</th>
            <th>Rola</th>       
            <th>Status</th>     
        </tr>
    </thead>
    <tbody>
        <?php foreach($users as $user): ?>
        <tr>
            <td><?php echo $user->id ?></td>
            <td><?php echo $user->name ?></td>
            <td><?php echo $user->username ?></td>
            <td><?php echo $user->email ?></td>
            <td><?php echo $user->role_id ?></td>
            <td><?php echo $user->user_status_id ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>