<?php
    $title = "UČESNICI KOLABORACIJE"; 
    $this->headTitle($title);
?>

<h1 class="page-title"><?php echo $this->escapeHtml($title) ?></h1>
<?php if($members->count() == 0): ?>
	<p>Nažalost, tabela članova je prazna.</p>
<?php else: ?>
	<table class="table">
    <thead>
        <tr>
            <th>R.br.</th>
            <th>Ime</th>
            <th>Vrsta učesnika</th>
            <th>Uloga</th>
            <th>Tip svojine</th>       
            <th>Web strana</th>     
            <th>Status</th>
            <th>Akcija</th>
        </tr>
    </thead>
    
    <tbody>
        <?php foreach($members as $member): ?>
        <tr>
            <td><?= $member['id'] ?></td>
            <td><?= $member['name'] ?></td>
            <td><?= $member['member_type'] ?></td>
            <td><?= $member['member_role'] ?></td>
            <td><?= $member['property'] ?></td>
            <td><?= $member['url'] ?></td>
            <td><?= $member['member_status'] ?></td>
            <td><a href="<?php echo $this->url('member', ['action' => 'editWithModel', 'id' => $member['id']]) ?>">Promeni</a> |
            <a href="<?php echo $this->url('member', ['action' => 'deleteWithModel', 'id' => $member['id']]) ?>">Obriši</a></td>                        
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<a class="btn btn-primary" href="<?php echo $this->url('member', ['action' => 'addWithModel'])?>">Dodaj novog učesnika</a>
<?php endif;?>
<div class="modal fade" id="myModal" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title">Brisanje korisnika</h4>
			</div>
			<div class="modal-body">
				<p>Korisnik će biti potpuno obrisan iz baze, bez mogućnosti povratka podataka. Da li ste sigurni?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-confirm" data-dismiss="modal">Yes</button>
				<button type="button" class="btn btn-cancel" data-dismiss="modal">No</button>
			</div>
		</div>
	</div>
</div>
<script>
$(document).ready(function() {
	$('a#delete').on('click', function(e) {
        e.preventDefault();
        path = $(e.target).attr('href');
        //console.log(path);
        $('#myModal').modal('show');
    });

	$('.btn-confirm').on('click', function(e) {        
        //alert(path);
        window.location.href = path;
    });
});
</script>

